allowBuilds:
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - '@expo/cli@56.1.13'
  - '@expo/package-manager@1.12.1'
  - '@expo/prebuild-config@56.0.14'
  - '@expo/ui@56.0.15'
  - expo-linking@56.0.13
  - expo-modules-core@56.0.14
  - expo-router@56.2.8
  - expo@56.0.7
  - oxlint-plugin-react-doctor@0.2.11
  - react-doctor@0.2.11
nodeLinker: hoisted
overrides:
  lightningcss: 1.30.1

